// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workoutTrackerService.proto

package workoutTrackerService;

public interface MealCaloriesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MealCaloriesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 dailyCalories = 1;</code>
   */
  int getDailyCalories();
}
