// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workoutTrackerService.proto

package workoutTrackerService;

/**
 * Protobuf type {@code MealCaloriesResponse}
 */
public  final class MealCaloriesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MealCaloriesResponse)
    MealCaloriesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MealCaloriesResponse.newBuilder() to construct.
  private MealCaloriesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MealCaloriesResponse() {
    dailyCalories_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MealCaloriesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            dailyCalories_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return workoutTrackerService.WorkoutTrackerProtoService.internal_static_MealCaloriesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return workoutTrackerService.WorkoutTrackerProtoService.internal_static_MealCaloriesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            workoutTrackerService.MealCaloriesResponse.class, workoutTrackerService.MealCaloriesResponse.Builder.class);
  }

  public static final int DAILYCALORIES_FIELD_NUMBER = 1;
  private int dailyCalories_;
  /**
   * <code>int32 dailyCalories = 1;</code>
   */
  public int getDailyCalories() {
    return dailyCalories_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dailyCalories_ != 0) {
      output.writeInt32(1, dailyCalories_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dailyCalories_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, dailyCalories_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof workoutTrackerService.MealCaloriesResponse)) {
      return super.equals(obj);
    }
    workoutTrackerService.MealCaloriesResponse other = (workoutTrackerService.MealCaloriesResponse) obj;

    boolean result = true;
    result = result && (getDailyCalories()
        == other.getDailyCalories());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DAILYCALORIES_FIELD_NUMBER;
    hash = (53 * hash) + getDailyCalories();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static workoutTrackerService.MealCaloriesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static workoutTrackerService.MealCaloriesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static workoutTrackerService.MealCaloriesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static workoutTrackerService.MealCaloriesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static workoutTrackerService.MealCaloriesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static workoutTrackerService.MealCaloriesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static workoutTrackerService.MealCaloriesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static workoutTrackerService.MealCaloriesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static workoutTrackerService.MealCaloriesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static workoutTrackerService.MealCaloriesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static workoutTrackerService.MealCaloriesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static workoutTrackerService.MealCaloriesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(workoutTrackerService.MealCaloriesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MealCaloriesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MealCaloriesResponse)
      workoutTrackerService.MealCaloriesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return workoutTrackerService.WorkoutTrackerProtoService.internal_static_MealCaloriesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return workoutTrackerService.WorkoutTrackerProtoService.internal_static_MealCaloriesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              workoutTrackerService.MealCaloriesResponse.class, workoutTrackerService.MealCaloriesResponse.Builder.class);
    }

    // Construct using workoutTrackerService.MealCaloriesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dailyCalories_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return workoutTrackerService.WorkoutTrackerProtoService.internal_static_MealCaloriesResponse_descriptor;
    }

    @java.lang.Override
    public workoutTrackerService.MealCaloriesResponse getDefaultInstanceForType() {
      return workoutTrackerService.MealCaloriesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public workoutTrackerService.MealCaloriesResponse build() {
      workoutTrackerService.MealCaloriesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public workoutTrackerService.MealCaloriesResponse buildPartial() {
      workoutTrackerService.MealCaloriesResponse result = new workoutTrackerService.MealCaloriesResponse(this);
      result.dailyCalories_ = dailyCalories_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof workoutTrackerService.MealCaloriesResponse) {
        return mergeFrom((workoutTrackerService.MealCaloriesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(workoutTrackerService.MealCaloriesResponse other) {
      if (other == workoutTrackerService.MealCaloriesResponse.getDefaultInstance()) return this;
      if (other.getDailyCalories() != 0) {
        setDailyCalories(other.getDailyCalories());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      workoutTrackerService.MealCaloriesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (workoutTrackerService.MealCaloriesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int dailyCalories_ ;
    /**
     * <code>int32 dailyCalories = 1;</code>
     */
    public int getDailyCalories() {
      return dailyCalories_;
    }
    /**
     * <code>int32 dailyCalories = 1;</code>
     */
    public Builder setDailyCalories(int value) {
      
      dailyCalories_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 dailyCalories = 1;</code>
     */
    public Builder clearDailyCalories() {
      
      dailyCalories_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MealCaloriesResponse)
  }

  // @@protoc_insertion_point(class_scope:MealCaloriesResponse)
  private static final workoutTrackerService.MealCaloriesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new workoutTrackerService.MealCaloriesResponse();
  }

  public static workoutTrackerService.MealCaloriesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MealCaloriesResponse>
      PARSER = new com.google.protobuf.AbstractParser<MealCaloriesResponse>() {
    @java.lang.Override
    public MealCaloriesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MealCaloriesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MealCaloriesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MealCaloriesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public workoutTrackerService.MealCaloriesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

