// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workoutTrackerService.proto

package workoutTrackerService;

/**
 * Protobuf type {@code MealRequest}
 */
public  final class MealRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MealRequest)
    MealRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MealRequest.newBuilder() to construct.
  private MealRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MealRequest() {
    meal_ = "";
    serving_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MealRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            meal_ = s;
            break;
          }
          case 16: {

            serving_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return workoutTrackerService.WorkoutTrackerProtoService.internal_static_MealRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return workoutTrackerService.WorkoutTrackerProtoService.internal_static_MealRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            workoutTrackerService.MealRequest.class, workoutTrackerService.MealRequest.Builder.class);
  }

  public static final int MEAL_FIELD_NUMBER = 1;
  private volatile java.lang.Object meal_;
  /**
   * <code>string meal = 1;</code>
   */
  public java.lang.String getMeal() {
    java.lang.Object ref = meal_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      meal_ = s;
      return s;
    }
  }
  /**
   * <code>string meal = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMealBytes() {
    java.lang.Object ref = meal_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      meal_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVING_FIELD_NUMBER = 2;
  private int serving_;
  /**
   * <code>int32 serving = 2;</code>
   */
  public int getServing() {
    return serving_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMealBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, meal_);
    }
    if (serving_ != 0) {
      output.writeInt32(2, serving_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMealBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, meal_);
    }
    if (serving_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, serving_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof workoutTrackerService.MealRequest)) {
      return super.equals(obj);
    }
    workoutTrackerService.MealRequest other = (workoutTrackerService.MealRequest) obj;

    boolean result = true;
    result = result && getMeal()
        .equals(other.getMeal());
    result = result && (getServing()
        == other.getServing());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MEAL_FIELD_NUMBER;
    hash = (53 * hash) + getMeal().hashCode();
    hash = (37 * hash) + SERVING_FIELD_NUMBER;
    hash = (53 * hash) + getServing();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static workoutTrackerService.MealRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static workoutTrackerService.MealRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static workoutTrackerService.MealRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static workoutTrackerService.MealRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static workoutTrackerService.MealRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static workoutTrackerService.MealRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static workoutTrackerService.MealRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static workoutTrackerService.MealRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static workoutTrackerService.MealRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static workoutTrackerService.MealRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static workoutTrackerService.MealRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static workoutTrackerService.MealRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(workoutTrackerService.MealRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MealRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MealRequest)
      workoutTrackerService.MealRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return workoutTrackerService.WorkoutTrackerProtoService.internal_static_MealRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return workoutTrackerService.WorkoutTrackerProtoService.internal_static_MealRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              workoutTrackerService.MealRequest.class, workoutTrackerService.MealRequest.Builder.class);
    }

    // Construct using workoutTrackerService.MealRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      meal_ = "";

      serving_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return workoutTrackerService.WorkoutTrackerProtoService.internal_static_MealRequest_descriptor;
    }

    @java.lang.Override
    public workoutTrackerService.MealRequest getDefaultInstanceForType() {
      return workoutTrackerService.MealRequest.getDefaultInstance();
    }

    @java.lang.Override
    public workoutTrackerService.MealRequest build() {
      workoutTrackerService.MealRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public workoutTrackerService.MealRequest buildPartial() {
      workoutTrackerService.MealRequest result = new workoutTrackerService.MealRequest(this);
      result.meal_ = meal_;
      result.serving_ = serving_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof workoutTrackerService.MealRequest) {
        return mergeFrom((workoutTrackerService.MealRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(workoutTrackerService.MealRequest other) {
      if (other == workoutTrackerService.MealRequest.getDefaultInstance()) return this;
      if (!other.getMeal().isEmpty()) {
        meal_ = other.meal_;
        onChanged();
      }
      if (other.getServing() != 0) {
        setServing(other.getServing());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      workoutTrackerService.MealRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (workoutTrackerService.MealRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object meal_ = "";
    /**
     * <code>string meal = 1;</code>
     */
    public java.lang.String getMeal() {
      java.lang.Object ref = meal_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        meal_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string meal = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMealBytes() {
      java.lang.Object ref = meal_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        meal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string meal = 1;</code>
     */
    public Builder setMeal(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      meal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string meal = 1;</code>
     */
    public Builder clearMeal() {
      
      meal_ = getDefaultInstance().getMeal();
      onChanged();
      return this;
    }
    /**
     * <code>string meal = 1;</code>
     */
    public Builder setMealBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      meal_ = value;
      onChanged();
      return this;
    }

    private int serving_ ;
    /**
     * <code>int32 serving = 2;</code>
     */
    public int getServing() {
      return serving_;
    }
    /**
     * <code>int32 serving = 2;</code>
     */
    public Builder setServing(int value) {
      
      serving_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 serving = 2;</code>
     */
    public Builder clearServing() {
      
      serving_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MealRequest)
  }

  // @@protoc_insertion_point(class_scope:MealRequest)
  private static final workoutTrackerService.MealRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new workoutTrackerService.MealRequest();
  }

  public static workoutTrackerService.MealRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MealRequest>
      PARSER = new com.google.protobuf.AbstractParser<MealRequest>() {
    @java.lang.Override
    public MealRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MealRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MealRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MealRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public workoutTrackerService.MealRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

