// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workoutTrackerService.proto

package workoutTrackerService;

public interface MealRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MealRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string meal = 1;</code>
   */
  java.lang.String getMeal();
  /**
   * <code>string meal = 1;</code>
   */
  com.google.protobuf.ByteString
      getMealBytes();

  /**
   * <code>int32 serving = 2;</code>
   */
  int getServing();
}
