// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workoutTrackerService.proto

package workoutTrackerService;

public interface WorkoutDetailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WorkoutDetailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string workout_name = 1;</code>
   */
  java.lang.String getWorkoutName();
  /**
   * <code>string workout_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getWorkoutNameBytes();

  /**
   * <code>double duration = 3;</code>
   */
  double getDuration();
}
