// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workoutTrackerService.proto

package workoutTrackerService;

public final class WorkoutTrackerProtoService {
  private WorkoutTrackerProtoService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WorkoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WorkoutResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033workoutTrackerService.proto\";\n\016Workout" +
      "Request\022\024\n\014workout_name\030\001 \001(\t\022\023\n\013allOrSi" +
      "ngle\030\004 \001(\010\"?\n\017WorkoutResponse\022\024\n\014workout" +
      "_name\030\001 \001(\t\022\026\n\016calorie_amount\030\003 \001(\0052O\n\025W" +
      "orkoutTrackerService\0226\n\013WorkoutList\022\017.Wo" +
      "rkoutRequest\032\020.WorkoutResponse\"\000(\0010\001B5\n\025" +
      "workoutTrackerServiceB\032WorkoutTrackerPro" +
      "toServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_WorkoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WorkoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WorkoutRequest_descriptor,
        new java.lang.String[] { "WorkoutName", "AllOrSingle", });
    internal_static_WorkoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WorkoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WorkoutResponse_descriptor,
        new java.lang.String[] { "WorkoutName", "CalorieAmount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
