// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workoutTrackerService.proto

package workoutTrackerService;

public interface WorkoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WorkoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string workout_name = 1;</code>
   */
  java.lang.String getWorkoutName();
  /**
   * <code>string workout_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getWorkoutNameBytes();

  /**
   * <code>bool allOrSingle = 4;</code>
   */
  boolean getAllOrSingle();
}
