// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workoutTrackerService.proto

package workoutTrackerService;

public interface WorkoutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WorkoutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string workout_name = 1;</code>
   */
  java.lang.String getWorkoutName();
  /**
   * <code>string workout_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getWorkoutNameBytes();

  /**
   * <code>int32 calorie_amount = 3;</code>
   */
  int getCalorieAmount();
}
