// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workoutTrackerService.proto

package workoutTrackerService;

/**
 * Protobuf type {@code WorkoutRequest}
 */
public  final class WorkoutRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WorkoutRequest)
    WorkoutRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WorkoutRequest.newBuilder() to construct.
  private WorkoutRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WorkoutRequest() {
    workoutName_ = "";
    allOrSingle_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WorkoutRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            workoutName_ = s;
            break;
          }
          case 32: {

            allOrSingle_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return workoutTrackerService.WorkoutTrackerProtoService.internal_static_WorkoutRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return workoutTrackerService.WorkoutTrackerProtoService.internal_static_WorkoutRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            workoutTrackerService.WorkoutRequest.class, workoutTrackerService.WorkoutRequest.Builder.class);
  }

  public static final int WORKOUT_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object workoutName_;
  /**
   * <code>string workout_name = 1;</code>
   */
  public java.lang.String getWorkoutName() {
    java.lang.Object ref = workoutName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      workoutName_ = s;
      return s;
    }
  }
  /**
   * <code>string workout_name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getWorkoutNameBytes() {
    java.lang.Object ref = workoutName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      workoutName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALLORSINGLE_FIELD_NUMBER = 4;
  private boolean allOrSingle_;
  /**
   * <code>bool allOrSingle = 4;</code>
   */
  public boolean getAllOrSingle() {
    return allOrSingle_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWorkoutNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, workoutName_);
    }
    if (allOrSingle_ != false) {
      output.writeBool(4, allOrSingle_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWorkoutNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, workoutName_);
    }
    if (allOrSingle_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, allOrSingle_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof workoutTrackerService.WorkoutRequest)) {
      return super.equals(obj);
    }
    workoutTrackerService.WorkoutRequest other = (workoutTrackerService.WorkoutRequest) obj;

    boolean result = true;
    result = result && getWorkoutName()
        .equals(other.getWorkoutName());
    result = result && (getAllOrSingle()
        == other.getAllOrSingle());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WORKOUT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getWorkoutName().hashCode();
    hash = (37 * hash) + ALLORSINGLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAllOrSingle());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static workoutTrackerService.WorkoutRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static workoutTrackerService.WorkoutRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static workoutTrackerService.WorkoutRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static workoutTrackerService.WorkoutRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static workoutTrackerService.WorkoutRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static workoutTrackerService.WorkoutRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static workoutTrackerService.WorkoutRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static workoutTrackerService.WorkoutRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static workoutTrackerService.WorkoutRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static workoutTrackerService.WorkoutRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static workoutTrackerService.WorkoutRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static workoutTrackerService.WorkoutRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(workoutTrackerService.WorkoutRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WorkoutRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WorkoutRequest)
      workoutTrackerService.WorkoutRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return workoutTrackerService.WorkoutTrackerProtoService.internal_static_WorkoutRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return workoutTrackerService.WorkoutTrackerProtoService.internal_static_WorkoutRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              workoutTrackerService.WorkoutRequest.class, workoutTrackerService.WorkoutRequest.Builder.class);
    }

    // Construct using workoutTrackerService.WorkoutRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      workoutName_ = "";

      allOrSingle_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return workoutTrackerService.WorkoutTrackerProtoService.internal_static_WorkoutRequest_descriptor;
    }

    @java.lang.Override
    public workoutTrackerService.WorkoutRequest getDefaultInstanceForType() {
      return workoutTrackerService.WorkoutRequest.getDefaultInstance();
    }

    @java.lang.Override
    public workoutTrackerService.WorkoutRequest build() {
      workoutTrackerService.WorkoutRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public workoutTrackerService.WorkoutRequest buildPartial() {
      workoutTrackerService.WorkoutRequest result = new workoutTrackerService.WorkoutRequest(this);
      result.workoutName_ = workoutName_;
      result.allOrSingle_ = allOrSingle_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof workoutTrackerService.WorkoutRequest) {
        return mergeFrom((workoutTrackerService.WorkoutRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(workoutTrackerService.WorkoutRequest other) {
      if (other == workoutTrackerService.WorkoutRequest.getDefaultInstance()) return this;
      if (!other.getWorkoutName().isEmpty()) {
        workoutName_ = other.workoutName_;
        onChanged();
      }
      if (other.getAllOrSingle() != false) {
        setAllOrSingle(other.getAllOrSingle());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      workoutTrackerService.WorkoutRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (workoutTrackerService.WorkoutRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object workoutName_ = "";
    /**
     * <code>string workout_name = 1;</code>
     */
    public java.lang.String getWorkoutName() {
      java.lang.Object ref = workoutName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workoutName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string workout_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWorkoutNameBytes() {
      java.lang.Object ref = workoutName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workoutName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string workout_name = 1;</code>
     */
    public Builder setWorkoutName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      workoutName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string workout_name = 1;</code>
     */
    public Builder clearWorkoutName() {
      
      workoutName_ = getDefaultInstance().getWorkoutName();
      onChanged();
      return this;
    }
    /**
     * <code>string workout_name = 1;</code>
     */
    public Builder setWorkoutNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      workoutName_ = value;
      onChanged();
      return this;
    }

    private boolean allOrSingle_ ;
    /**
     * <code>bool allOrSingle = 4;</code>
     */
    public boolean getAllOrSingle() {
      return allOrSingle_;
    }
    /**
     * <code>bool allOrSingle = 4;</code>
     */
    public Builder setAllOrSingle(boolean value) {
      
      allOrSingle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool allOrSingle = 4;</code>
     */
    public Builder clearAllOrSingle() {
      
      allOrSingle_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WorkoutRequest)
  }

  // @@protoc_insertion_point(class_scope:WorkoutRequest)
  private static final workoutTrackerService.WorkoutRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new workoutTrackerService.WorkoutRequest();
  }

  public static workoutTrackerService.WorkoutRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WorkoutRequest>
      PARSER = new com.google.protobuf.AbstractParser<WorkoutRequest>() {
    @java.lang.Override
    public WorkoutRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WorkoutRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WorkoutRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WorkoutRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public workoutTrackerService.WorkoutRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

