// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workoutTrackerService.proto

package workoutTrackerService;

public interface WorkoutDetailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WorkoutDetailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 burnedCalories = 1;</code>
   */
  int getBurnedCalories();
}
