// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartFridgeService.proto

package smartFridgeService;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product = 1;</code>
   */
  java.lang.String getProduct();
  /**
   * <code>string product = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductBytes();

  /**
   * <code>int32 stock_status = 2;</code>
   */
  int getStockStatus();
}
