// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartFridgeService.proto

package smartFridgeService;

public interface ProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product = 1;</code>
   */
  java.lang.String getProduct();
  /**
   * <code>string product = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductBytes();
}
