// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartFridgeService.proto

package smartFridgeService;

public interface ProductRequestNoParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductRequestNoParam)
    com.google.protobuf.MessageOrBuilder {
}
