// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gymRoomControlService.proto

package gymRoomControlService;

public final class GymRoomProtoService {
  private GymRoomProtoService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TempResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033gymRoomControlService.proto\" \n\013TempReq" +
      "uest\022\021\n\ttempInput\030\001 \001(\005\"\"\n\014TempResponse\022" +
      "\022\n\ntempOutput\030\001 \001(\005\"6\n\014LightRequest\022&\n\020t" +
      "urnLightRequest\030\001 \001(\0162\014.LightStatus\"8\n\rL" +
      "ightResponse\022\'\n\021turnLightResponse\030\001 \001(\0162" +
      "\014.LightStatus*\036\n\013LightStatus\022\006\n\002on\020\000\022\007\n\003" +
      "off\020\0012u\n\016GymRoomService\0221\n\016changeRoomTem" +
      "p\022\014.TempRequest\032\r.TempResponse\"\000(\001\0220\n\017tu" +
      "rnOnOffLights\022\r.LightRequest\032\016.LightResp" +
      "onseB.\n\025gymRoomControlServiceB\023GymRoomPr" +
      "otoServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TempRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TempRequest_descriptor,
        new java.lang.String[] { "TempInput", });
    internal_static_TempResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TempResponse_descriptor,
        new java.lang.String[] { "TempOutput", });
    internal_static_LightRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightRequest_descriptor,
        new java.lang.String[] { "TurnLightRequest", });
    internal_static_LightResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_LightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightResponse_descriptor,
        new java.lang.String[] { "TurnLightResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
