// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gymRoomControlService.proto

package gymRoomControlService;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool turnLightOn = 1;</code>
   */
  boolean getTurnLightOn();
}
