// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gymRoomControlService.proto

package gymRoomControlService;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.LightStatus turnLightRequest = 1;</code>
   */
  int getTurnLightRequestValue();
  /**
   * <code>.LightStatus turnLightRequest = 1;</code>
   */
  gymRoomControlService.LightStatus getTurnLightRequest();
}
