// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gymRoomControlService.proto

package gymRoomControlService;

public interface LightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool turnLightOff = 1;</code>
   */
  boolean getTurnLightOff();
}
