// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gymRoomControlService.proto

package gymRoomControlService;

public interface LightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.LightStatus turnLightResponse = 1;</code>
   */
  int getTurnLightResponseValue();
  /**
   * <code>.LightStatus turnLightResponse = 1;</code>
   */
  gymRoomControlService.LightStatus getTurnLightResponse();
}
