// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gymRoomControlService.proto

package gymRoomControlService;

/**
 * Protobuf type {@code LightResponse}
 */
public  final class LightResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LightResponse)
    LightResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LightResponse.newBuilder() to construct.
  private LightResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LightResponse() {
    turnLightResponse_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LightResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            turnLightResponse_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gymRoomControlService.GymRoomProtoService.internal_static_LightResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gymRoomControlService.GymRoomProtoService.internal_static_LightResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gymRoomControlService.LightResponse.class, gymRoomControlService.LightResponse.Builder.class);
  }

  public static final int TURNLIGHTRESPONSE_FIELD_NUMBER = 1;
  private int turnLightResponse_;
  /**
   * <code>.LightStatus turnLightResponse = 1;</code>
   */
  public int getTurnLightResponseValue() {
    return turnLightResponse_;
  }
  /**
   * <code>.LightStatus turnLightResponse = 1;</code>
   */
  public gymRoomControlService.LightStatus getTurnLightResponse() {
    @SuppressWarnings("deprecation")
    gymRoomControlService.LightStatus result = gymRoomControlService.LightStatus.valueOf(turnLightResponse_);
    return result == null ? gymRoomControlService.LightStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (turnLightResponse_ != gymRoomControlService.LightStatus.on.getNumber()) {
      output.writeEnum(1, turnLightResponse_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (turnLightResponse_ != gymRoomControlService.LightStatus.on.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, turnLightResponse_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gymRoomControlService.LightResponse)) {
      return super.equals(obj);
    }
    gymRoomControlService.LightResponse other = (gymRoomControlService.LightResponse) obj;

    boolean result = true;
    result = result && turnLightResponse_ == other.turnLightResponse_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TURNLIGHTRESPONSE_FIELD_NUMBER;
    hash = (53 * hash) + turnLightResponse_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gymRoomControlService.LightResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gymRoomControlService.LightResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gymRoomControlService.LightResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gymRoomControlService.LightResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gymRoomControlService.LightResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gymRoomControlService.LightResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gymRoomControlService.LightResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gymRoomControlService.LightResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gymRoomControlService.LightResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gymRoomControlService.LightResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gymRoomControlService.LightResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gymRoomControlService.LightResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gymRoomControlService.LightResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LightResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LightResponse)
      gymRoomControlService.LightResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gymRoomControlService.GymRoomProtoService.internal_static_LightResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gymRoomControlService.GymRoomProtoService.internal_static_LightResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gymRoomControlService.LightResponse.class, gymRoomControlService.LightResponse.Builder.class);
    }

    // Construct using gymRoomControlService.LightResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      turnLightResponse_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gymRoomControlService.GymRoomProtoService.internal_static_LightResponse_descriptor;
    }

    @java.lang.Override
    public gymRoomControlService.LightResponse getDefaultInstanceForType() {
      return gymRoomControlService.LightResponse.getDefaultInstance();
    }

    @java.lang.Override
    public gymRoomControlService.LightResponse build() {
      gymRoomControlService.LightResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gymRoomControlService.LightResponse buildPartial() {
      gymRoomControlService.LightResponse result = new gymRoomControlService.LightResponse(this);
      result.turnLightResponse_ = turnLightResponse_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gymRoomControlService.LightResponse) {
        return mergeFrom((gymRoomControlService.LightResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gymRoomControlService.LightResponse other) {
      if (other == gymRoomControlService.LightResponse.getDefaultInstance()) return this;
      if (other.turnLightResponse_ != 0) {
        setTurnLightResponseValue(other.getTurnLightResponseValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gymRoomControlService.LightResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gymRoomControlService.LightResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int turnLightResponse_ = 0;
    /**
     * <code>.LightStatus turnLightResponse = 1;</code>
     */
    public int getTurnLightResponseValue() {
      return turnLightResponse_;
    }
    /**
     * <code>.LightStatus turnLightResponse = 1;</code>
     */
    public Builder setTurnLightResponseValue(int value) {
      turnLightResponse_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.LightStatus turnLightResponse = 1;</code>
     */
    public gymRoomControlService.LightStatus getTurnLightResponse() {
      @SuppressWarnings("deprecation")
      gymRoomControlService.LightStatus result = gymRoomControlService.LightStatus.valueOf(turnLightResponse_);
      return result == null ? gymRoomControlService.LightStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.LightStatus turnLightResponse = 1;</code>
     */
    public Builder setTurnLightResponse(gymRoomControlService.LightStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      turnLightResponse_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.LightStatus turnLightResponse = 1;</code>
     */
    public Builder clearTurnLightResponse() {
      
      turnLightResponse_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LightResponse)
  }

  // @@protoc_insertion_point(class_scope:LightResponse)
  private static final gymRoomControlService.LightResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gymRoomControlService.LightResponse();
  }

  public static gymRoomControlService.LightResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LightResponse>
      PARSER = new com.google.protobuf.AbstractParser<LightResponse>() {
    @java.lang.Override
    public LightResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LightResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LightResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LightResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gymRoomControlService.LightResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

