// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gymRoomControlService.proto

package gymRoomControlService;

public interface TempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TempRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tempInput = 1;</code>
   */
  int getTempInput();
}
