// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gymRoomControlService.proto

package gymRoomControlService;

public interface TempResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TempResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tempOutput = 1;</code>
   */
  int getTempOutput();
}
