// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gymRoomControlService.proto

package gymRoomControlService;

public interface TempResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TempResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tempOutput = 1;</code>
   */
  java.lang.String getTempOutput();
  /**
   * <code>string tempOutput = 1;</code>
   */
  com.google.protobuf.ByteString
      getTempOutputBytes();
}
